import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
function fn(n){const m=html.match(new RegExp('^  (?:async )?function '+n+'\\(','m'));assert.ok(m,n);const a=m.index,line=html.slice(a,html.indexOf('\n',a));if(line.trimEnd().endsWith('}'))return line;return html.slice(a,html.indexOf('\n  }',a)+4);}
const names=['vendorCategoryValid','vendorCategoryOptions','vendorMutationGuard','bindVendorExpenseDefault','saveVendorCategory','vendorClassificationHtml','saveEntryCategory','confirmVendorBackfill','addVendor','addExpenseEntry','addQuickExpenseEntry','checkedBusinessMutation','expenseCategoryLabel','renderVendorManage'];
function setup(respond=()=>({data:[{id:'v1',default_category:'food'}],error:null})){
 const queries=[],toasts=[],inputs={},state={store:'A',authProfile:{user_id:'u1'},month:'2026-09',vendors:[{id:'v1',name:'동원',defaultCategory:'food'},{id:'v2',name:'카드지출',defaultCategory:'per_entry'}],expenseEntries:[{id:'e1',date:'2026-09-10',description:'동원',amount:100,category:null},{id:'e2',date:'2026-09-10',description:'동원',amount:50,category:'other'},{id:'e3',date:'2026-09-10',description:'카드지출',amount:30,category:null}]};
 let confirmation,allowed=true,renders=0;
 const ctx=vm.createContext({state,console,Set,Number,document:{getElementById:id=>inputs[id]},currentStoreId:()=>state.store,monthKey:()=>state.month,monthDateRange:()=>({start:'2026-09-01',end:'2026-09-30'}),bizToday:()=> '2026-09-24',MANEE_STAFF_AUTH_ENABLED:true,canManageBusinessData:()=>allowed,escapeHtml:s=>String(s).replaceAll('<','&lt;').replaceAll('"','&quot;'),render:()=>renders++,showToast:s=>toasts.push(s),askConfirm:(s,cb)=>{confirmation={s,cb};},db:{from:table=>{const log={table,ops:[]};queries.push(log);const q=new Proxy({}, {get:(_,k)=>k==='then'?(yes,no)=>Promise.resolve(respond(log)).then(yes,no):(...args)=>{log.ops.push([k,...args]);return q;}});return q;}}});
 vm.runInContext(html.match(/  const EXPENSE_CATEGORIES = \[[\s\S]*?\n  \];/)[0]+'\nlet maneeViewEpoch=0;const vendorMutationLocks=new Set();\n'+names.map(fn).join('\n')+'\nthis.api={'+names.join(',')+'};',ctx);
 return {state,inputs,queries,toasts,api:ctx.api,ctx,confirmation:()=>confirmation,renders:()=>renders,deny:()=>allowed=false};
}
test('ordinary vendors show default label; per-entry alone shows classify and per-purchase controls',()=>{const h=setup();assert.doesNotMatch(h.api.vendorClassificationHtml('동원',true),/분류하기/);assert.match(h.api.vendorClassificationHtml('동원',true),/식자재/);assert.match(h.api.vendorClassificationHtml('카드지출',true),/분류하기/);h.state.classifyVendor='카드지출';assert.match(h.api.vendorClassificationHtml('카드지출',true),/data-saveentrycategory="e3"/);assert.doesNotMatch(h.api.vendorClassificationHtml('카드지출',false),/분류하기/);});
test('unconfigured vendors stay unconfigured and prompt setup; no name guessing',()=>{const h=setup();h.state.vendors[0].defaultCategory=null;assert.match(h.api.vendorClassificationHtml('동원',true),/설정해/);assert.doesNotMatch(h.api.vendorClassificationHtml('동원',true),/분류하기/);});
test('default selection works for both input forms and remains overridable',()=>{for(const prefix of ['','quick-']){const h=setup(),v={value:'v1'},c={value:'',options:[{text:''}]};h.inputs[prefix+'expense-vendor-select']=v;h.inputs[prefix+'expense-category-select']=c;h.api.bindVendorExpenseDefault(prefix);assert.equal(c.value,'food');c.value='other';assert.equal(c.value,'other');v.value='v2';v.onchange();assert.equal(c.value,'');assert.equal(c.options[0].text,'나중에 분류');}});
test('default update changes only vendor, preserves classified and unclassified history',async()=>{const h=setup();h.inputs['vendor-category-v1']={value:'food'};const before=JSON.stringify(h.state.expenseEntries);await h.api.saveVendorCategory('v1');assert.equal(JSON.stringify(h.state.expenseEntries),before);assert.equal(h.queries[0].table,'vendors');assert.ok(h.queries[0].ops.some(o=>o[0]==='eq'&&o[1]==='store_id'&&o[2]==='A'));});
test('failed/zero-row save leaves category unchanged',async()=>{for(const r of [{data:[],error:null},{data:null,error:{message:'denied'}}]){const h=setup(()=>r);h.inputs['vendor-category-v1']={value:'other'};await h.api.saveVendorCategory('v1');assert.equal(h.state.vendors[0].defaultCategory,'food');assert.equal(h.inputs['vendor-category-v1'].value,'food');assert.ok(h.toasts.some(x=>x.includes('실패')));}});
test('duplicate save sends one query and stale store reply cannot update UI',async()=>{let resolve;const h=setup(()=>new Promise(r=>resolve=r));h.inputs['vendor-category-v1']={value:'other'};const a=h.api.saveVendorCategory('v1');await h.api.saveVendorCategory('v1');await new Promise(r=>setImmediate(r));assert.equal(h.queries.length,1);h.state.store='B';resolve({data:[{id:'v1',default_category:'other'}],error:null});await a;assert.equal(h.state.vendors[0].defaultCategory,'food');assert.equal(h.renders(),0);});
test('account/month/loader changes invalidate response guard',()=>{for(const change of [h=>h.state.authProfile.user_id='u2',h=>h.state.month='2026-10',h=>h.state.vendors=[],h=>vm.runInContext('maneeViewEpoch++',h.ctx)]){const h=setup(),alive=h.api.vendorMutationGuard();change(h);assert.equal(alive(),false);}});
test('invalid category and staff cannot update vendor',async()=>{const h=setup();h.inputs['vendor-category-v1']={value:'bad'};await h.api.saveVendorCategory('v1');h.inputs['vendor-category-v1'].value='other';h.deny();await h.api.saveVendorCategory('v1');assert.equal(h.queries.length,0);});
test('backfill requires confirmation and only affects confirmed unclassified IDs with store/month/null filters',async()=>{const h=setup(()=>({data:[{id:'e1'}],error:null}));h.api.confirmVendorBackfill('v1');assert.equal(h.queries.length,0);assert.match(h.confirmation().s,/1건 · 100원/);await h.confirmation().cb();assert.equal(h.state.expenseEntries[0].category,'food');assert.equal(h.state.expenseEntries[1].category,'other');for(const op of ['gte','lte','in','is'])assert.ok(h.queries[0].ops.some(x=>x[0]===op));assert.ok(h.queries[0].ops.some(x=>x[0]==='is'&&x[1]==='category'&&x[2]===null));});
test('switching context before confirming cancels the write',async()=>{const h=setup();h.api.confirmVendorBackfill('v1');h.state.store='B';await h.confirmation().cb();assert.equal(h.queries.length,0);});
test('per-entry save never overwrites an already classified DB row',async()=>{const h=setup(()=>({data:[],error:null}));h.inputs['entry-category-e3']={value:'supplies'};await h.api.saveEntryCategory('e3');assert.equal(h.state.expenseEntries[2].category,null);assert.ok(h.queries[0].ops.some(x=>x[0]==='is'&&x[1]==='category'));});
test('new vendor requires explicit setting and saves it with store scope',async()=>{const h=setup(()=>({data:{id:'new',name:'새 거래처',default_category:'per_entry'},error:null}));h.inputs['new-vendor-input']={value:'새 거래처'};h.inputs['new-vendor-category']={value:''};await h.api.addVendor();assert.equal(h.queries.length,0);h.inputs['new-vendor-category'].value='per_entry';await h.api.addVendor();assert.equal(h.state.vendors.at(-1).defaultCategory,'per_entry');});
test('per-entry purchases may be saved unclassified for later classification; amounts unchanged',async()=>{for(const prefix of ['','quick-']){const h=setup(q=>({data:{id:'new',date:'2026-09-24',category:q.ops.find(x=>x[0]==='insert')[1].category},error:null}));h.inputs[prefix+'expense-vendor-select']={value:'v2',selectedIndex:0,options:[{text:'카드지출'}]};h.inputs[prefix+'expense-amount-input']={value:'1000'};h.inputs[prefix+'expense-category-select']={value:''};await h.api[prefix?'addQuickExpenseEntry':'addExpenseEntry']();assert.equal(h.state.expenseEntries.at(-1).amount,1000);assert.equal(h.state.expenseEntries.at(-1).category,null);}});
test('all inline JavaScript parses',()=>{for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(m[1].trim())new vm.Script(m[1]);});
